Allow type annotations in generators and discriminators
Replaces calls to  `inspect.getargspec` with `inspect.getfullargspec`.

This allows users to add type annotations to the generator and discriminator functions, for instance:

```
def generator_fn(noise_dict: Mapping[str, tf.Tensor],
                 mode: tf.estimator.ModeKeys) -> tf.Tensor:
  ...

def discriminator_fn(data: tf.Tensor, unused_conditioning: Optional[tf.Tensor],
                     mode: tf.estimator.ModeKeys) -> tf.Tensor:
  ...
```

Calls to `inspect.getargspec` with a function with type annotations causes an exception to be raised:

```
ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
```

Additionally, this should stop the following deprecation warnings when training estimators:

```
DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
```
PiperOrigin-RevId: 388469119
Change-Id: I2eb0d77c0c1975aa26f2c2121fb575486242cd93